spring:
  redis:
    host: 172.16.10.77
    port: 6379
    password: 123456
    jedis:
      pool:
        max-active: 200 #最大连接数
        max-wait: -1    #最大等待阻塞时间
        max-idle: 10    #最大空闲连接
        min-idle: 0     #最小空闲时间
    timeout: 1000       #连接超时时间